TaskManagerASP/Models/TaskViewModels.cs
using System;

namespace TaskManagerASP.Models
{
    public class TaskShortIndexViewModel
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public int RequiredHours { get; set; }
    }
    public class TaskIndexViewModel : TaskShortIndexViewModel
    {
        public int ExecutitiveId { get; set; }
        public int CreatorId { get; set; }
        public string ExecutitiveName { get; set; }
        public string CreatorName { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime LastEditedOn { get; set; }
        public bool IsCompleted { get; set; }
    }
}

TaskManagerASP/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Data.Entities.Entities;
using Microsoft.AspNetCore.Http;
using TaskManagerASP.Filters;
using TaskManagerASP.Models;
using TaskManagerASP.Tools;

namespace TaskManagerASP.Controllers
{
    public class TasksController : BaseCRUDController<Task, TaskIndexViewModel>
    {


        protected override Expression<Func<Task, TaskIndexViewModel>> ViewModelQuery
        {
            get
            {
                return t => new TaskIndexViewModel()
                {
                    Id = t.Id,
                    Header = t.Header,
                    Description = t.Description,
                    CreatorName = $"{t.Creator.FirstName} {t.Creator.LastName}",
                    ExecutitiveName = $"{t.Executitive.FirstName} {t.Executitive.LastName}",
                    CreatorId = t.CreatorId,
                    ExecutitiveId = t.ExecutitiveId,
                    RequiredHours = t.RequiredHours,
                    CreatedOn = t.CreatedOn,
                    LastEditedOn = t.LastEditedOn,
                    IsCompleted = t.IsCompleted
                };
            }
        }

        protected override Task ParseToEntity(TaskIndexViewModel item)
        {
            return new Task()
            {
                Id = item.Id,
                Header = item.Header,
                Description = item.Description,
                CreatorId = item.CreatorId,
                ExecutitiveId = item.ExecutitiveId,
                RequiredHours = item.RequiredHours,
                CreatedOn = item.CreatedOn,
                LastEditedOn = item.LastEditedOn,
                IsCompleted = item.IsCompleted
            };
        }
        protected override bool HasAccess(Task task)
        {
            int parentId = AuthenticationManager.GetLoggedUser(HttpContext).Id;
            if (task.CreatorId == parentId || task.ExecutitiveId == parentId)
            {
                return true;
            }
            return false;
           
        }

        [Log]
        [HttpGet]
        public IActionResult Index( int? itemsPerPage,
                                    string search = null,
                                    bool description = false,
                                    bool header = false,
                                    int page = 1,
                                    string sort = null)
        {
            //if (!IsAuthorized())
            //{
            //    return RedirectToAction("Login", "Home");
            //}
            int itemsAmount;
            if (itemsPerPage != null)
            {
                this.HttpContext.Session.SetInt32("itemsPerPage", itemsPerPage.Value);
                itemsAmount = itemsPerPage.Value;
            }
            else
            {
                itemsAmount = this.HttpContext.Session.GetInt32("itemsPerPage") ?? Constants.DefaultItemsPerPage;
            }



            
            TaskOrderOptions sortOption = TaskOrderOptions.HeaderAsc;
            
            if(sort != null)
                try
                {
                    sortOption = (TaskOrderOptions) Enum.Parse(typeof(TaskOrderOptions), sort);
                }
                catch (Exception)
                {
                    // ignored
                }

            Expression<Func<Task, dynamic>> order = null;
            var descending = false;
            switch (sortOption)
            {
                case TaskOrderOptions.HeaderAsc:
                    order = i => i.Header;
                    break;
                case TaskOrderOptions.HeaderDesc:
                    order = i => i.Header;
                    descending = true;
                    break;
                case TaskOrderOptions.DescriptionDesc:
                    order = i => i.Description;
                    descending = true;
                    break;
                case TaskOrderOptions.DescriptionAsc:
                    order = i => i.Description;
                    break;
                case TaskOrderOptions.RequiredHoursAsc:
                    order = i => i.RequiredHours;
                    break;
                case TaskOrderOptions.RequiredHoursDesc:
                    order = i => i.RequiredHours;
                    descending = true;
                    break;
            }
            int parentId = AuthenticationManager.GetLoggedUser(HttpContext).Id;
            Expression<Func<Task, bool>> where = t => (t.CreatorId == parentId || t.ExecutitiveId == parentId);
            if (!string.IsNullOrEmpty(search))
            {
                if (header && description)
                    where = t => t.Header.StartsWith(search) || t.Description.StartsWith(search) && (t.CreatorId == parentId || t.ExecutitiveId == parentId);
                else if (header)
                    where = t => t.Header.StartsWith(search) && (t.CreatorId == parentId || t.ExecutitiveId == parentId);
                else if(description)
                    where = t => t.Description.StartsWith(search) && (t.CreatorId == parentId || t.ExecutitiveId == parentId);
            }
            ICollection<TaskIndexViewModel> model = new List<TaskIndexViewModel>();
            int itemsAvaliable;
            using (var repo = base.GetRepository())
            {
                var result =
                    repo.GetAllPaged(
                        where: where,
                        orderByKeySelector: order,
                        descending: descending,
                        page: page,
                        itemsPerPage: itemsAmount,
                        select: this.ViewModelQuery
                        );
                model = result.Item1;
                itemsAvaliable = result.Item2;
            }

            ViewData["CurrentPage"] = page;
            ViewData["PagesAvaliable"] = (int)Math.Ceiling((double)itemsAvaliable / itemsAmount);
            
            return View(model);
        }
        [HttpPost]
        public override IActionResult Create(Task task)
        {
            task.CreatedOn = DateTime.Now;
            task.LastEditedOn = DateTime.Now;
            task.CreatorId = AuthenticationManager.GetLoggedUser(HttpContext).Id;

            return base.Create(task);
        }

        [HttpPost]
        public override IActionResult Edit(Task task)
        {
            task.LastEditedOn = DateTime.Now;

            return base.Edit(task);
        }
    }
}

TaskManagerASP/ViewComponents/CommentsViewComponent.cs
using Data.Entities.Entities;
using Data.Entities.Repositories;
using Microsoft.AspNetCore.Mvc;
using TaskManagerASP.Models;
using TaskManagerASP.Tools;

namespace TaskManagerASP.ViewComponents
{
    public class CommentsViewComponent : ViewComponent
    {
        private IRepository<Comment> GetRepository() =>
            new RepositoryClient().GetRepositoryProvider().GetRepository<Comment>();

        public IViewComponentResult Invoke(int parentId)
        {
            using (var repo = GetRepository())
            {
                return View(repo.GetAll(where: i => i.TaskId == parentId));
            }
        }

    }
}

TaskManagerASP/Views/Tasks/Create.cshtml
@{
    ViewData["Title"] = "Add new task";
}
<h1>Create a new task</h1>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">@Html.ValidationSummary()</div>
}
@using (Html.BeginForm("Create", "Tasks", FormMethod.Post))
{
    @model Data.Entities.Entities.Task

    @Html.HiddenFor(m => m.Id, new { required = true })

    <div class="form-group">
        @Html.LabelFor(m => m.Header)
        @Html.TextBoxFor(m => m.Header, new { @class = "form-control", placeholder = "Proper header..", required = true })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "Detailed description.." })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.RequiredHours)
        @Html.TextBoxFor(m => m.RequiredHours, new { @class = "form-control", placeholder = "Detailed description.." })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ExecutitiveId)
        @Html.TextBoxFor(m => m.ExecutitiveId, new { @class = "form-control", placeholder = "Detailed description.." })
    </div>

    <input type="submit" class="btn btn-primary" value="Create" />
}
<a asp-controller="Tasks" asp-action="Index"><button class="btn btn-warning">Cancel</button></a>

TaskManagerASP/Views/Tasks/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h2>Task details</h2>
@{ 
    @model TaskManagerASP.Models.TaskIndexViewModel
}
<h4>Header:</h4>
@Html.DisplayFor(m => Model.Header, new { @class = "well" })
<br /><br />
<h4>Description</h4>
@Html.DisplayFor(m => Model.Description, new { @class = "well" })
<br /><br />
<h4>Required hours</h4>
@Html.DisplayFor(m => Model.RequiredHours, new { @class = "well" })
<br /><br />
<h4>Executitive</h4>
@Html.DisplayFor(m => Model.ExecutitiveName, new { @class = "well" })
<br /><br />
<h4>Creator</h4>
@Html.DisplayFor(m => Model.CreatorName, new { @class = "well" })
<br /><br />
<h4>Created on</h4>
@Html.DisplayFor(m => Model.CreatedOn, new { @class = "well" })
<br /><br />
<h4>Last edited</h4>
@Html.DisplayFor(m => Model.LastEditedOn, new { @class = "well" })
<br /><br />
<h4>Status</h4>
@if (Model.IsCompleted)
{
    <div class="well">Completed</div>
}
else
{

    <div class="well">In process</div>
}

<h4>Comments</h4>
<div class="well">
    @await Component.InvokeAsync("Comments", new {parentId = Model.Id})
</div>

<h5>Add new comment</h5>
<div class="well">

    @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
    {
        @Html.Hidden("TaskId", Model.Id)
        @Html.TextArea("Body", new { @class = "form-control" })
        <br />
            <input type="submit" class="btn btn-primary" />
    }

</div>

TaskManagerASP/Views/Tasks/Edit.cshtml
@{
    ViewData["Title"] = "Edit task";
}

<h2>Edit</h2>

@if (!ViewData.ModelState.IsValid)
            {
    <div class="alert alert-danger">@Html.ValidationSummary()</div>
}

@using (Html.BeginForm("Edit", "Tasks", FormMethod.Post))
{
    @model Data.Entities.Entities.Task
        
    @Html.HiddenFor(m => m.Id, new {type = "hidden", required = true})
    @Html.HiddenFor(m => m.CreatedOn, new {type = "hidden", required = true})

    <div class="form-group">
        @Html.LabelFor(m => m.Header)
        @Html.EditorFor(m => m.Header, new {@class = "form-control", placeholder = "Proper header..", required = true})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new {@class = "form-control", placeholder = "Detailed description.."})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.RequiredHours)
        @Html.EditorFor(m => m.RequiredHours, new {@class = "form-control", placeholder = "Detailed description.."})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ExecutitiveId)
        @Html.EditorFor(m => m.ExecutitiveId, new {@class = "form-control", placeholder = "Detailed description.."})
    </div>

    <input type="submit" class="btn btn-primary" value="Edit"/>
}
<a asp-controller="Tasks" asp-action="Index"><button class="btn btn-warning">Cancel</button></a>

TaskManagerASP/Views/Tasks/Index.cshtml
@model ICollection<TaskManagerASP.Models.TaskIndexViewModel>
@{
    
    ViewData["Title"] = "Tasks";
}
<h2>Tasks</h2>
@if (ViewData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@ViewData["ErrorMessage"].ToString()</div>
}

<div class="well">
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
            Items per Page
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            @foreach (var amount in TaskManagerASP.Tools.Constants.AmountOfItemsPerPage)
            {
                <li>@Html.ActionLink(amount.ToString(), "Index", "Tasks", new { page = ViewData["CurrentPage"] })</li>
            }
        </ul>
    </div>
    <div class="well-sm">
        <form class="form-control" method="get" asp-controller="Tasks" asp-action="Index">
            Search By:
            @if (Context.Request.Query["header"] == "true")
            {
                <label class="checkbox-inline"><input type="checkbox" name="header" value="true" checked>Header</label>
            }
            else
            {
                <label class="checkbox-inline"><input type="checkbox" name="header" value="true">Header</label>
            }
            @if (Context.Request.Query["description"] == "true")
            {
                <label class="checkbox-inline"><input type="checkbox" name="description" value="true" checked>Description</label>
            }
            else
            {
                <label class="checkbox-inline"><input type="checkbox" name="description" value="true">Description</label>
            }

            

            <input type="text" name="search" value="@Context.Request.Query["search"]"/>
            <input type="submit" value="Search"/>
        </form>
    </div>
</div>
<ul>
    Order by
    <li>
        Header:
        @Html.ActionLink("", "Index", "Tasks", new {sort = TaskManagerASP.Tools.TaskOrderOptions.HeaderAsc}, new {@class = "glyphicon glyphicon-sort-by-alphabet"})
        @Html.ActionLink("", "Index", "Tasks", new {sort = TaskManagerASP.Tools.TaskOrderOptions.HeaderDesc}, new {@class = "glyphicon glyphicon-sort-by-alphabet-alt"})
    </li>
    <li>
        Description:
        @Html.ActionLink("", "Index", "Tasks", new { sort = TaskManagerASP.Tools.TaskOrderOptions.DescriptionAsc }, new { @class = "glyphicon glyphicon-sort-by-alphabet" })
        @Html.ActionLink("", "Index", "Tasks", new { sort = TaskManagerASP.Tools.TaskOrderOptions.DescriptionDesc }, new { @class = "glyphicon glyphicon-sort-by-alphabet-alt" })
    </li>
    <li>
        Required hours:
        @Html.ActionLink("", "Index", "Tasks", new { sort = TaskManagerASP.Tools.TaskOrderOptions.RequiredHoursAsc }, new { @class = "glyphicon glyphicon-sort-by-order" })
        @Html.ActionLink("", "Index", "Tasks", new { sort = TaskManagerASP.Tools.TaskOrderOptions.RequiredHoursDesc }, new { @class = "glyphicon glyphicon-sort-by-order-alt" })
    </li>
</ul>
@foreach(var item in Model)
    {
    <div class="panel panel-default">
        <div class="panel-body">
            <h3>Header</h3>
            
            @Html.LabelFor(m => item.Header)<br />
            @Html.DisplayFor(m => item.Header)
            <hr />
            @Html.LabelFor(m => item.RequiredHours)<br/>
            @Html.DisplayFor(m => item.RequiredHours)
            <hr />
            @Html.LabelFor(m => item.Description)<br />
            <small style="color: #aaa;">@Html.DisplayFor(m => item.Description)</small><br /><br />
            @Html.ActionLink("Details", "Details", "Tasks", new { id = item.Id}, new{ @class = "btn btn-info" })
            @Html.ActionLink("Edit", "Edit", "Tasks", new { id = item.Id}, new { @class = "btn btn-warning" })
            @Html.ActionLink("Delete", "Delete", "Tasks", new {id=item.Id }, new { @class = "btn btn-danger", type = "button" })
        </div>
    </div>
    }

<ul class="pagination">
    @for (int i = 1; i <= (int)ViewData["PagesAvaliable"]; i++)
    {
        if (i == (int)ViewData["CurrentPage"])
        {
            <li class="active">
                @Html.ActionLink(i.ToString(), "Index", "Tasks", new
           {
               header = Context.Request.Query["header"],
               description = Context.Request.Query["description"],
               search = Context.Request.Query["search"],
               sort = Context.Request.Query["sort"],
               page = i
           })
            </li>
        }
        else
        {
            <li>@Html.ActionLink(i.ToString(), "Index", "Tasks", new
           {
               header = Context.Request.Query["header"],
               description = Context.Request.Query["description"],
               search = Context.Request.Query["search"],
               sort = Context.Request.Query["sort"],
               page = i
           })</li>
        }

    }
</ul>
<a asp-controller="Tasks" asp-action="Create" ><button class="btn btn-primary">Create new task</button></a>