TaskManagerASP/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Data.Entities.Entities;
using Microsoft.AspNetCore.Http;
using TaskManagerASP.Filters;
using TaskManagerASP.Models;
using TaskManagerASP.Tools;

namespace TaskManagerASP.Controllers
{
    public class TasksController : BaseCRUDController<Task, TaskIndexViewModel>
    {


        protected override Expression<Func<Task, TaskIndexViewModel>> ViewModelQuery
        {
            get
            {
                return t => new TaskIndexViewModel()
                {
                    Id = t.Id,
                    Header = t.Header,
                    Description = t.Description,
                    CreatorName = $"{t.Creator.FirstName} {t.Creator.LastName}",
                    ExecutitiveName = $"{t.Executitive.FirstName} {t.Executitive.LastName}",
                    CreatorId = t.CreatorId,
                    ExecutitiveId = t.ExecutitiveId,
                    RequiredHours = t.RequiredHours,
                    CreatedOn = t.CreatedOn,
                    LastEditedOn = t.LastEditedOn,
                    IsCompleted = t.IsCompleted
                };
            }
        }

        protected override Task ParseToEntity(TaskIndexViewModel item)
        {
            return new Task()
            {
                Id = item.Id,
                Header = item.Header,
                Description = item.Description,
                CreatorId = item.CreatorId,
                ExecutitiveId = item.ExecutitiveId,
                RequiredHours = item.RequiredHours,
                CreatedOn = item.CreatedOn,
                LastEditedOn = item.LastEditedOn,
                IsCompleted = item.IsCompleted
            };
        }
        protected override bool HasAccess(Task task)
        {
            int parentId = AuthenticationManager.GetLoggedUser(HttpContext).Id;
            if (task.CreatorId == parentId || task.ExecutitiveId == parentId)
            {
                return true;
            }
            return false;
           
        }

        [Log]
        [HttpGet]
        public IActionResult Index( int? itemsPerPage,
                                    string search = null,
                                    bool description = false,
                                    bool header = false,
                                    int page = 1,
                                    string sort = null)
        {
            //if (!IsAuthorized())
            //{
            //    return RedirectToAction("Login", "Home");
            //}
            int itemsAmount;
            if (itemsPerPage != null)
            {
                this.HttpContext.Session.SetInt32("itemsPerPage", itemsPerPage.Value);
                itemsAmount = itemsPerPage.Value;
            }
            else
            {
                itemsAmount = this.HttpContext.Session.GetInt32("itemsPerPage") ?? Constants.DefaultItemsPerPage;
            }



            
            TaskOrderOptions sortOption = TaskOrderOptions.HeaderAsc;
            
            if(sort != null)
                try
                {
                    sortOption = (TaskOrderOptions) Enum.Parse(typeof(TaskOrderOptions), sort);
                }
                catch (Exception)
                {
                    // ignored
                }

            Expression<Func<Task, dynamic>> order = null;
            var descending = false;
            switch (sortOption)
            {
                case TaskOrderOptions.HeaderAsc:
                    order = i => i.Header;
                    break;
                case TaskOrderOptions.HeaderDesc:
                    order = i => i.Header;
                    descending = true;
                    break;
                case TaskOrderOptions.DescriptionDesc:
                    order = i => i.Description;
                    descending = true;
                    break;
                case TaskOrderOptions.DescriptionAsc:
                    order = i => i.Description;
                    break;
                case TaskOrderOptions.RequiredHoursAsc:
                    order = i => i.RequiredHours;
                    break;
                case TaskOrderOptions.RequiredHoursDesc:
                    order = i => i.RequiredHours;
                    descending = true;
                    break;
            }
            int parentId = AuthenticationManager.GetLoggedUser(HttpContext).Id;
            Expression<Func<Task, bool>> where = t => (t.CreatorId == parentId || t.ExecutitiveId == parentId);
            if (!string.IsNullOrEmpty(search))
            {
                if (header && description)
                    where = t => t.Header.StartsWith(search) || t.Description.StartsWith(search) && (t.CreatorId == parentId || t.ExecutitiveId == parentId);
                else if (header)
                    where = t => t.Header.StartsWith(search) && (t.CreatorId == parentId || t.ExecutitiveId == parentId);
                else if(description)
                    where = t => t.Description.StartsWith(search) && (t.CreatorId == parentId || t.ExecutitiveId == parentId);
            }
            ICollection<TaskIndexViewModel> model = new List<TaskIndexViewModel>();
            int itemsAvaliable;
            using (var repo = base.GetRepository())
            {
                var result =
                    repo.GetAllPaged(
                        where: where,
                        orderByKeySelector: order,
                        descending: descending,
                        page: page,
                        itemsPerPage: itemsAmount,
                        select: this.ViewModelQuery
                        );
                model = result.Item1;
                itemsAvaliable = result.Item2;
            }

            ViewData["CurrentPage"] = page;
            ViewData["PagesAvaliable"] = (int)Math.Ceiling((double)itemsAvaliable / itemsAmount);
            
            return View(model);
        }
        [HttpPost]
        public override IActionResult Create(Task task)
        {
            task.CreatedOn = DateTime.Now;
            task.LastEditedOn = DateTime.Now;
            task.CreatorId = AuthenticationManager.GetLoggedUser(HttpContext).Id;

            return base.Create(task);
        }

        [HttpPost]
        public override IActionResult Edit(Task task)
        {
            task.LastEditedOn = DateTime.Now;

            return base.Edit(task);
        }
    }
}

TaskManagerASP/Controllers/UsersController.cs
using System;
using System.Linq.Expressions;
using Data.Entities.Entities;
using TaskManagerASP.Filters;
using TaskManagerASP.Models;
using TaskManagerASP.Tools;

namespace TaskManagerASP.Controllers
{
    [Authorize(ShouldBeAdmin = true)]
    public class UsersController : BaseCRUDController<User, UserIndexViewModel>
    {
        protected override Expression<Func<User, UserIndexViewModel>> ViewModelQuery { get
        {
            return u => new UserIndexViewModel()
            {
                Id = u.Id,
                FirstName = u.FirstName,
                LastName = u.LastName,
                Username = u.UserName,
                IsAdmin = u.IsAdmin
            };
        } }
        protected override User ParseToEntity(UserIndexViewModel item)
        {
            return new User()
            {
                Id = item.Id,
                FirstName = item.FirstName,
                LastName = item.LastName,
                UserName = item.Username,
                IsAdmin = item.IsAdmin
            };
        }
        //protected override bool IsAuthorized()
        //{
        //    if (!AuthenticationManager.GetLoggedUser(HttpContext).IsAdmin)
        //    {
        //        ViewData["ErrorMessage"] = ErrorMessages.ShouldBeAdmin;
        //        return false;
        //    }
        //    return base.IsAuthorized();
        //}
    }
}

TaskManagerASP/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagerASP</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TaskManagerASP</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - TaskManagerASP</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

TaskManagerASP/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagerASP</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TaskManagerASP</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (TaskManagerASP.Models.AuthenticationManager.GetLoggedUser(Context) == null)
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Login">Login</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Register">Register</a></li>
                    }
                    else
                    {
                        @if (TaskManagerASP.Models.AuthenticationManager.GetLoggedUser(Context).IsAdmin)
                        {
                            <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        }
                        <li><a asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Logout">Logout</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Task Manager - ASP.NET Core Application</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>